development:
 adapter: mysql2
 database: qms_dev
 pool: 5
 username: root
 password: l1nuX.03o7?a
 host: localhost
 socket: /var/run/mysqld/mysqld.sock

test:
 adapter: mysql2
 database: qms_test
 pool: 5
 username: root
 password: l1nuX.03o7?a
 host: localhost
 socket: /var/run/mysqld/mysqld.sock

production:
 adapter: mysql2
 database: qms_prod
 pool: 5
 username: root
 password: l1nuX.03o7?a
 host: localhost
 socket: /var/run/mysqld/mysqld.sock